---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package:
        name: nginx
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Verify NGINX is up and running
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200

    - name: Check if NGINX Management Suite services are installed
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)
      loop:
        - nms
        - nms-core
        - nms-dpm
        - nms-ingestion
        - nms-integrations
        - nms-acm

    - name: Verify NGINX Management Suite modules are loaded
      ansible.builtin.uri:
        url: https://localhost/modules
        status_code: 200
        validate_certs: false
        return_content: yes
        body_format: json
      register: response
      failed_when: '("API Connectivity Manager" and "Security Monitoring") not in (response.json | map(attribute="name") | list)'
