---
- name: Converge
  hosts: all
  tasks:
    - name: Uninstall NMS
      ansible.builtin.include_role:
        name: ansible-role-nginx-management-suite
      vars:
        nms_setup: uninstall
        nms_user_passwd: 'Password123'
        nms_remove_certs: false
        nginx_remove_license: false
        nginx_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
