---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package:
        name: nginx
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Verify NGINX is up and running
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200

    - name: Check if NGINX Management Suite services are no longer installed
      ansible.builtin.service_facts:
      register: systemd_services
      failed_when: item in systemd_services.ansible_facts.services
      loop:
        - nms.service
        - nms-core.service
        - nms-dpm.service
        - nms-ingestion.service
        - nms-integrations.service
