---
- name: (Debian/Ubuntu) {{ (nms_cleanup_status is defined) | ternary('Remove', 'Configure') }} NGINX Management Suite Apt repository
  ansible.builtin.apt_repository:
    repo: "{{ nms_debian_signing_key_repo }}"
    state: "{{ nms_cleanup_status | default('present') }}"
    update_cache: false
    filename: nms

- name: (Debian/Ubuntu) Download apt configuration
  ansible.builtin.get_url:
    url: "{{ nms_debian_apt_config_url }}"
    dest: "{{ nms_debian_apt_config_path }}"
    checksum: sha256:0f7f07891dfdb01579231d9a3366a5675062e46616fca04116197cf369a70e35 # curl -sL https://download.docker.com/linux/ubuntu/gpg|sha256sum
  when: nms_cleanup_status is not defined

- name: (Debian/Ubuntu) {{ nms_setup | capitalize }} NGINX Instance Manager
  ansible.builtin.apt:
    name: "nms-instance-manager{{ (nms_version != '') | ternary('=' + nms_version , '') }}"
    update_cache: yes
    allow_downgrade: "{{ omit if ansible_version.full is version('2.12', '<') else true }}"
    state: "{{ nms_state }}"
  register: nms_install_state
  when: nms_cleanup_status is not defined

- name: (Debian/Ubuntu) Make sure NGINX Instance Manager is running
  ansible.builtin.systemd:
    state: started
    name: nms
    enabled: true
  notify: Restart NGINX
  when: nms_cleanup_status is not defined
