---
- name: (Debian/Ubuntu) Installing prerequisites required for changing password
  ansible.builtin.apt:
    name: python3-passlib
  tags:
    - nms_config_password

- name: Render credentials using 'htpasswd'
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/nms-password-render.yml"
  tags:
    - nms_config_password
