---
- name: Generate a random string with 1 lower, 1 upper, 1 number and 1 special char (atleast)
  block:
    - ansible.builtin.set_fact:
        nms_password: "{{ (nms_password | length > 0) | ternary(nms_password, lookup('community.general.random_string', override_special='!#$%&()*+,-./:;<=>?@[]^_{|}~', min_lower=1, min_upper=1, min_special=1, min_numeric=1, length=12)) }}"
    - name: Printing password for each host
      ansible.builtin.debug:
        var: nms_password
    - name: Add a user to a password file and ensure permissions are set
      community.general.htpasswd:
        path: "{{ nms_cred_path }}"
        name: "{{ nms_username }}"
        password: "{{nms_password}}"
      notify:
        - Restart NGINX Management Suite
    - name: Login credentials
      ansible.builtin.debug:
        msg: "The login for {{ ansible_host }}: {{ nms_username }} / {{ nms_password }}"
  when: nms_force_password | bool or nms_install_state is defined and nms_install_state.changed | bool
  tags:
    - nms_config_password
