---
- name: (RHEL8+) Installing prerequisites required for changing password
  block:
    - name: (RHEL8+) Installing 'pip'
      ansible.builtin.yum:
        name:
          - python3-pip
    - name: (RHEL8+) Installing 'passlib' for password configuration
      ansible.builtin.pip:
        name: passlib
  when: ansible_facts['distribution_major_version'] >= '8'
  tags:
    - nms_config_password

- name: (Amazon/RHEL7/Oracle Linux) Installing prerequisites required for changing password
  block:
    - name: (Amazon/RHEL7/Oracle Linux) Get version 2.7 'pip' script
      ansible.builtin.get_url:
        url: "{{ nms_redhat7_pip27 }}"
        dest: "/tmp/get-pip.py"
    - name: Check if 'pip' binary exists
      ansible.builtin.stat:
        path: /usr/bin/pip
      ignore_errors: true
      register: pip
    - name: (Amazon/RHEL7/Oracle Linux) Install 'pip' version 2.7
      ansible.builtin.shell: "python get-pip.py"
      args:
        chdir: /tmp/
      when: not pip.stat.exists
    - name: (Amazon/RHEL7/Oracle Linux) Installing 'passlib' for password configuration
      ansible.builtin.pip:
        name: passlib
  when:  ansible_facts['distribution_major_version'] <= '7'
  tags:
    - nms_config_password

- name: Render credentials using 'htpasswd'
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/nms-password-render.yml"
  tags:
    - nms_config_password
