---
# To force a admin credential change. Disabled by default.
nms_force_password: false

# Initial NMS password
nms_user_passwd: ''

# Intiail NMS username
nms_user_name: admin

# Location where htpasswd file path
nms_cred_path: /etc/nms/nginx/.htpasswd

# NMS installation defaults to the latest version. You can specify a specific version using the proper glob
# nms_version: 2.4.0*
nms_version: ''

# Clickhouse is an external database required for NMS. That is a third party app that changes fast. As a result, we are pinning it to version 22.9.2.7.
## Clickhouse installation is enabled by default
nms_clickhouse_install: true

## If you want to use the latest, it can be commented out or specify a blank string.
## nms_clickhouse_version: ''
nms_clickhouse_version: '22.8.5.29'

## Default to long term support. You can use either 'lts' or 'stable'.
nms_clickhouse_release_kind: lts

## By default, NMS certificates are removed by default
nms_remove_certs: true

## By default, no NMS modules are installed.
## If 'version' is not set or is absent, the latest version is installed.
## If 'setup' is not set or is absent, the value from the nms_setup is used.
## If modules need to be installed from a different repository, set 'yum_repo' or 'apt_repo'.
## 'yum_gpgcheck' and 'apt_verify' are additional apt and yum options that can also be set.
##   Valid inputs are 'true' or 'false'. If these aren't defined, it will use the default values
##   from the 'ansible.builtin.yum_repository' or 'ansible.builtin.apt_repository' modules.
nms_modules: []
  # - name: acm
  #   version: ''
  #   setup: install
  # - name: sm
  #   version: ''
  #   setup: install
  # - name: acm
  #   yum_repo: install
  #   yum_gpgcheck: false
  # - name: acm
  #   apt_repo: install
  #   apt_validate: false
