---
- name: Restart NGINX Management Suite
  ansible.builtin.systemd:
    name: nms
    state: restarted
  loop: "{{ nms_services | flatten(levels=1) }}"
- name: Restart NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted
