---
- name: Converge
  hosts: all
  tasks:
    - name: Install NMS
      ansible.builtin.include_role:
        name: ansible-role-nginx-management-suite
      vars:
        nms_version: 2.4.0*
        nms_setup: install
        nms_password: 'Password123'
        nginx_selinux: true
        nginx_selinux_enforcing: false
        nginx_remove_license: false
        nginx_license:
            certificate: license/nginx-repo.crt
            key: license/nginx-repo.key
