---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package:
        name: nginx
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Verify NGINX is up and running
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200

    - name: Check if NGINX Management Suite services are installed
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)
      loop:
        - nms
        - nms-core
        - nms-dpm
        - nms-ingestion
        - nms-integrations

    - name: Verify NGINX Management Suite is up and running
      ansible.builtin.uri:
        url: https://localhost
        status_code: 200
        validate_certs: no

    - name: (RedHat) Verify correct version of NGINX has been installed
      ansible.builtin.command: rpm -qa nms-instance-manager
      changed_when: false
      register: version
      failed_when: version.stdout is search('2.4.0')
      when: ansible_facts['os_family'] == 'RedHat'

    - name: (Debian) Verify correct version of NGINX has been installed
      ansible.builtin.shell: dpkg -s nms-instance-manager | grep -i version
      changed_when: false
      register: version
      failed_when: version.stdout is search('2.4.0')
      when: ansible_facts['os_family'] == 'Debian'
