---
driver:
  name: docker
lint: |
  set -e
  ansible-lint --force-color .
platforms:
  # NMS
  - name: ubuntu-jammy
    image: ubuntu:jammy
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    docker_networks:
      - name: hostname_network
        ipam_config:
          - subnet: '10.3.1.0/24'
            gateway: '10.3.1.254'
    networks:
      - name: bridge
      - name: hostname_network
    groups:
      - nms
    command: /sbin/init

# NGINX Instances
  - name: amazonlinux-2
    image: amazonlinux:2
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - data
      - data_r27
    networks:
      - name: bridge
      - name: hostname_network
    command: /usr/sbin/init
  - name: centos-7
    image: centos:7
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - data
      - data_r27
    networks:
      - name: bridge
      - name: hostname_network
    command: /usr/sbin/init
  - name: rhel-9
    image: redhat/ubi9:9.1.0
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - data
      - data_r27
    networks:
      - name: bridge
      - name: hostname_network
    command: /usr/sbin/init
  - name: debian-bullseye
    image: debian:bullseye-slim
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - data
      - data_r25
    networks:
      - name: bridge
      - name: hostname_network
    command: /sbin/init
  - name: ubuntu-focal
    image: ubuntu:focal
    platform: x86_64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - data
      - data_r25
    networks:
      - name: bridge
      - name: hostname_network
    command: /sbin/init
provisioner:
  options:
    vvv: true
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
