- name: (Python 3) Install 'pip' package
  ansible.builtin.package:
    name: python3-pip

- name: (OracleLinux 8) Install setuptools package
  ansible.builtin.package:
    name: "python3.11-setuptools"
  when:
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "8"

- name: (OracleLinux 8) Install cryptography package
  ansible.builtin.package:
    name: "python3.11-cryptography"
  when:
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "8"

- name: (Python 3) Ensure 'pip' is updated
  ansible.builtin.pip:
    name: pip>=21.2.4
