- name: (Debian/Red Hat) Create SSL directory
  ansible.builtin.file:
    path: /etc/ssl/nginx
    state: directory
    mode: "0755"

- name: (Debian/Red Hat) Copy NGINX Plus certificate and license key
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/ssl/nginx
    decrypt: true
    mode: "0444"
  loop:
    - "{{ nginx_license['certificate'] }}"
    - "{{ nginx_license['key'] }}"

- name: (Debian/Red Hat) Install cryptography package
  ansible.builtin.pip:
    name: cryptography

- name: (OracleLinux 8) Install cryptography package
  ansible.builtin.pip:
    name: cryptography
    executable: /usr/bin/pip3.11
  when:
    - ansible_facts['distribution'] == "OracleLinux"
    - ansible_facts['distribution_major_version'] == "8"

- name: (Debian/Red Hat) Check that NGINX Plus certificate is valid
  community.crypto.x509_certificate_info:
    path: /etc/ssl/nginx/nginx-repo.crt
  register: cert

- name: (Debian/Red Hat) Check that NGINX Plus key is valid
  community.crypto.openssl_privatekey_info:
    path: /etc/ssl/nginx/nginx-repo.key
  register: key

- name: (Debian/Red Hat) Check that NGINX Plus license is valid
  ansible.builtin.assert:
    that:
      - cert.expired == false
      - cert.public_key == key.public_key
    success_msg: Your NGINX Plus license is valid!
    fail_msg: Something went wrong! Make sure your NGINX Plus license is valid!
