---
- name: Verify controller has NGINX Instance Manager installed
  hosts: controller
  vars_files:
    - vars/nginx-controller.yml
    - vars/nim.yml

  tasks:
    # Role for installing/upgrading NGINX Instance Manager
    - ansible.builtin.include_role:
        name: install-nim

- name: Install NGINX Agent on data plane hosts
  hosts: data
  vars_files:
    - vars/nginx-data.yml
    - vars/nim.yml

  tasks:
    # Debug module to print out ansible specific variables.
    # - ansible.builtin.copy:
    #     content: "{{ hostvars[groups.controller[0]] | to_nice_json }}"
    #     dest: "/Users/jwong/dev/github/nginxinc/NGINX-Demos/nginx-plus-count/jwong-debug"
    #   delegate_to: localhost

    # NGINX Role for NGINX+ Install / Upgrade
    - ansible.builtin.include_role:
        name: nginxinc.nginx

    # Role for installing/upgrading NGINX Agent
    - ansible.builtin.include_role:
        name: install-agent
      vars:
        nms_fqdn: "{{ groups.controller[0] }}"
      tags:
        - data_nginx
