---
- name: (Debian/Ubuntu) {{ 'Remove' if nms_cleanup_status is defined or nms_state == 'absent' else 'Configure' }} NGINX Management Suite Apt repository
  ansible.builtin.apt_repository:
    repo: "{{ nms_repository_debian | default(nms_default_repository_debian) }}"
    state: "{{ nms_cleanup_status | default((nms_setup == 'uninstall') | ternary('absent', 'present')) }}"
    update_cache: false
    filename: nms

- name: (Debian/Ubuntu) {{ 'Remove' if nms_cleanup_status is defined or nms_state == 'absent' else 'Configure' }} NMS Module Apt repository
  ansible.builtin.apt_repository:
    repo: "{{ item.apt_repo | adm_deb_based_repo if item.name == 'adm' else item.apt_repo }}"
    state: "{{ nms_cleanup_status | default(nms_state if item.setup is not defined else nms_state_vals[item.setup]) }}"
    update_cache: false
    validate_certs: "{{ omit if item.apt_validate is not defined else item.apt_validate }}"
    filename: "nms-{{ item.name }}"
  loop: "{{ nms_modules }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nms_modules is defined
    - item.name == "adm" or item.apt_repo is defined

- name: (Debian/Ubuntu) {{ nms_cleanup_status is defined | ternary('Remove', 'Configure') }} NGINX Plus license verification
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/90nginx
    create: true
    block: |
      Acquire::https::{{ (nms_repository_debian | default(nms_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::Verify-Peer "true";
      Acquire::https::{{ (nms_repository_debian | default(nms_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::Verify-Host "true";
      Acquire::https::{{ (nms_repository_debian | default(nms_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::SslCert     "/etc/ssl/nginx/nginx-repo.crt";
      Acquire::https::{{ (nms_repository_debian | default(nms_default_repository_debian)) | regex_search('(?<=https://)[^/]*') }}::SslKey      "/etc/ssl/nginx/nginx-repo.key";
    state: "{{ nms_cleanup_status | default((nms_setup == 'uninstall') | ternary('absent', 'present')) }}"
    mode: "0444"

- name: (Debian/Ubuntu) {{ nms_setup | capitalize }} NGINX Instance Manager
  ansible.builtin.apt:
    name: "nms-instance-manager{{ (nms_version is not defined or nms_version == '') | ternary('', '=' + nms_version) }}"
    update_cache: true
    allow_downgrade: "{{ omit if ansible_version.full is version('2.12', '<') else true }}"
    state: "{{ nms_state }}"
  register: nms_install_state
  when: nms_cleanup_status is not defined
  notify:
    - Restart NGINX Management Suite
    - Restart NGINX

- name: (Debian/Ubuntu) {{ nms_setup if item.setup is not defined else item.setup | capitalize }} NMS Modules
  ansible.builtin.apt:
    name: "{{ nms_module_vals[item.name]['package_name'] }}{{ '' if (item.version is not defined or item.version == '') else '=' + item.version }}"
    update_cache: true
    allow_downgrade: "{{ omit if ansible_version.full is version('2.12', '<') else true }}"
    state: "{{ nms_state if item.setup is not defined else nms_state_vals[item.setup] }}"
  when:
    - nms_cleanup_status is not defined
    - nms_modules is defined
  loop: "{{ nms_modules }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Restart NGINX Management Suite
    - Restart NGINX

- name: (Debian/Ubuntu) Make sure NGINX Management Suite is {{ nms_service_state | capitalize }}
  ansible.builtin.systemd:
    state: "{{ nms_service_state }}"
    name: "{{ item }}"
    enabled: true
  notify: Restart NGINX
  loop: "{{ nms_services | flatten(levels=1) }}"
  when:
    - nms_cleanup_status is not defined
    - nms_setup | lower != 'uninstall'
