---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package:
        name: nginx
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is stopped
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Check if Clickhouse service is stopped
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)
      loop:
        - clickhouse-server

    - name: Check if NGINX Management Suite services are stopped
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)
      loop:
        - nms
        - nms-core
        - nms-dpm
        - nms-ingestion
        - nms-integrations
