---
- name: Converge
  hosts: all
  tasks:
    - name: Install NMS & Modules
      ansible.builtin.include_role:
        name: ansible-role-nginx-management-suite
      vars:
        nms_setup: install
        nms_user_passwd: 'Password123'
        nginx_selinux: true
        nginx_selinux_enforcing: false
        nms_remove_certs: false
        nginx_type: plus
        nginx_remove_license: false
        nginx_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
        nms_modules:
          - name: acm
          - name: sm
